vim.pack.add({
  {
    src = "https://github.com/rose-pine/neovim",
    name = "rose-pine",
  },
})

require("rose-pine").setup({
  highlight_groups = {
    ["@constructor"] = { fg = "text", inherit = false, bold = false, italic = false },
    ["@constant.builtin"] = { fg = "text", inherit = false, bold = false, italic = false },
    ["@function"] = { fg = "text" },
    ["@function.method"] = { fg = "text" },
    ["@function.builtin"] = { fg = "text", inherit = false, bold = false, italic = false },
    ["@function.method.call"] = { fg = "text", inherit = false, bold = false, italic = false },
    ["@keyword"] = { fg = "text" },
    ["@keyword.import"] = { fg = "text" },
    ["@keyword.exception"] = { fg = "text" },
    ["@keyword.operator"] = { fg = "text" },
    ["@keyword.return"] = { fg = "text" },
    ["@keyword.conditional"] = { fg = "text" },
    ["@parameter"] = { fg = "rose", inherit = false, bold = false, italic = false },
    ["@property"] = { fg = "text", inherit = false, bold = false, italic = false },
    ["@type"] = { fg = "text" },
    ["@type.builtin"] = { fg = "text", inherit = false, bold = false, italic = false },
    ["@variable"] = { fg = "text", inherit = false, bold = false, italic = false },
    ["@variable.builtin"] = { fg = "text", inherit = false, bold = false, italic = false },
    ["@variable.member"] = { fg = "text", inherit = false, bold = false, italic = false },
    ["@variable.parameter"] = { fg = "text", inherit = false, bold = false, italic = false },
    Normal = { fg = "text" },
    Comment = { fg = "gold", italic = true },
    String = { fg = "foam" },
    TSString = { fg = "foam" },
    Constant = { fg = "pine" },
    TSConstant = { fg = "pine" },
    Number = { fg = "iris" },
    TSNumber = { fg = "iris" },
    Boolean = { fg = "text" },
    TSBoolean = { fg = "text" },
    Type = { fg = "text" },
    TSType = { fg = "text" },
    Function = { fg = "text" },
    TSFunction = { fg = "text" },
    TSVariableBuiltin = { fg = "text" },
    Keyword = { fg = "text" },
    TSKeyword = { fg = "text" },
    Include = { fg = "text" },
    TSKeywordFunction = { fg = "text" },
    TSOperator = { fg = "text" },
    TSPunctDelimiter = { fg = "text" },
    TSField = { fg = "text" },
    TSProperty = { fg = "text" },
    Identifier = { fg = "text" },
    DiagnosticError = { fg = "love" },
    DiagnosticWarn = { fg = "gold" },
    LspDiagnosticsDefaultError = { fg = "love" },
  },
})

vim.cmd.colorscheme("rose-pine")
