require("config.options")
require("config.keymaps")
require("config.commands")
require("config.netrw")
require("core.lsp")

require("plugins.blink")
require("plugins.colorscheme")
require("plugins.comment")
require("plugins.gitsigns")
require("plugins.mason")
require("plugins.neotree")
require("plugins.refactoring")
require("plugins.telescope")
require("plugins.treesitter")
require("plugins.undotree")
require("plugins.dap").setup()
